# 不同环境多套配置,按application-{profile名}.yml命名
# 推荐使用环境变量的方式激活profiles
# export SPRING_PROFILES_ACTIVE = prod
spring:
  datasource:
    url: jdbc:mysql://localhost/tacocloud
    username: tacouser
    password: tacopassword
logging:
  level:
    tacos: WARN